easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Post
    site_name: 'Admin'
    design:
        menu:
            - { label: 'Home', url: '/' }
            - { entity: 'Post', params: { sortDirection: 'ASC' } }
       