easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Post
        - App\Entity\User
    site_name: 'Admin'
    design:
        menu:
            - { label: 'Posts',entity: 'Post', params: { sortDirection: 'DESC' } }
            - { label: 'Users',entity: 'User', params: { sortDirection: 'DESC' } }
            - { label: '< Back', url: '/' }
       