fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email: 
      address: 'phmarcano@gmail.com'
      sender_name: 'Pedro Hernandez'
    service:
        mailer: 'fos_user.mailer.noop'